export default {
    splashScreen: require('./img/intro.png'),
    logo: require('./img/logo.png'),
    slider1: require('./img/slider1.png'),
    slider2: require('./img/slider2.png'),
    slider3: require('./img/slider3.png'),
    slider4: require('./img/slider4.png'),
    backgroundLogin: require('./img/background.png'),
    checkBoxEmpty: require('./img/check-box-empty.png'),
    checkBox: require('./img/check-box.png'),
    sortDown: require('./img/down.png'),
    sortUp: require('./img/up.png'),
    indicate: require('./img/indicate.png'),
    addStaff: require('./img/addStaff.png'),
    closePopup: require('./img/closePopup.png'),
    logoTop: require('./img/fill-form-top.png'),
    camera: require('./img/camera.png'),
    iconUpload: require('./img/icon-upload.png'),
    signOut: require('./img/out.png'),
    openDrawer: require('./img/openDrawer.png'),
    plus: require('./img/plus.png'),
    sub: require('./img/sub.png'),
    calendar: require('./img/calendar.png'),
    iconItemBanner: require('./img/iconItemBanner.png'),
    deleteIconBanner: require('./img/deleteIconBanner.png'),
    arrowRight: require('./img/arrow_right.png'),
    search: require('./img/search.png'),
    export: require('./img/export.png'),
    dropdown: require('./img/dropdown.png'),
    arrowNote: require('./img/enter.png'),
    clearKeyboard: require('./img/clearKeyboard.png'),
    subKeyboard: require('./img/subKeyboard.png'),
    imagePlaceHolder: require('./img/imagePlaceHolder.png'),
    discountBtn: require('./img/discountBtn.png'),
    subAmount: require('./img/subAmount.png'),
    plusAmount: require('./img/plusAmount.png'),
    productBasket: require('./img/productBasket.png'),
    removeItemBasket: require('./img/removeItemBasket.png'),
    arrowRightButton: require('./img/arrowRightButton.png'),
    back: require('./img/back.png'),
    basketInvoice: require('./img/basketInvoice.png'),
    radioExport: require('./img/radioExport.png'),
    radioExportSe: require('./img/radioExportSe.png'),
    phoneContact: require('./img/phoneContact.png'),
    emailContact: require('./img/emailContact.png'),
    arrowLogDetail: require('./img/arrowLogDetail.png'),
    visaLogo: require('./img/visaLogo.png'),
    masterCardLogo: require('./img/masterCardLogo.png'),
    discoverLogo: require('./img/discoverLogo.png'),
    arrowReport: require('./img/arrowReport.png'),
    hpLogo: require('./img/hpLogo.png'),
    paxLogo: require('./img/paxLogo.png'),
    merchantLogo: require('./img/merchantLogo.png'),
    arrowDownAmount: require('./img/arrowDownAmount.png'),
    sale: require('./img/sale.png'),
    showPass: require('./img/showPass.png'),
    notShowPass: require('./img/notShowPass.png'),
    printInvoice: require('./img/printInvoice.png'),
    print_btn: require('./img/print_btn.png'),
    cashier_btn: require('./img/cashier_btn.png'),

    // --- drawer --
    Customer: require('./drawer/customer.png'),
    Home: require('./drawer/home.png'),
    Inventory: require('./drawer/inventory.png'),
    Invoice: require('./drawer/invoice.png'),
    Reports: require('./drawer/report.png'),
    Setting: require('./drawer/setting.png'),
    Settlement: require('./drawer/settlement.png'),
    Support: require('./drawer/support.png'),

    // --- setting --
    General: require('./setting/General.png'),
    General_in: require('./setting/General_in.png'),
    Staff: require('./setting/Staff.png'),
    Staff_in: require('./setting/Staff_in.png'),
    Services: require('./setting/Services.png'),
    Services_in: require('./setting/Services_in.png'),
    Payment: require('./setting/Payment.png'),
    Payment_in: require('./setting/Payment_in.png'),
    Hardware: require('./setting/Hardware.png'),
    Hardware_in: require('./setting/Hardware_in.png'),
    About: require('./setting/About.png'),
    About_in: require('./setting/About_in.png'),
    Logout: require('./setting/Logout.png'),
    Logout_in: require('./setting/Logout_in.png'),
    Extra: require('./setting/Extra.png'),
    Extra_in: require('./setting/Extra_in.png'),
    Categories: require('./setting/Categories.png'),
    Categories_in: require('./setting/Categories_in.png'),
    Pax: require('./setting/pax.png'),
    Barcode: require('./setting/barcode.png'),
    Print: require('./setting/print.png'),
    logoAbout: require('./setting/logoAbout.png'),
    TAX: require('./setting/TAX.png'),
    TAX_in: require('./setting/TAX_in.png'),


    // --- Place holder --
    extra_holder: require('./placeholder/extra_holder.png'),
    product_holder: require('./placeholder/product_holder.png'),
    service_holder: require('./placeholder/service_holder.png'),
    staff_holder: require('./placeholder/staff_holder.png'),

    // --- Support ---
    ContactUs_in: require('./support/ContactUs_in.png'),
    ContactUs: require('./support/ContactUs.png'),
    Documents_in: require('./support/Documents_in.png'),
    Documents: require('./support/Documents.png'),
    LiveChat_in: require('./support/LiveChat_in.png'),
    LiveChat: require('./support/LiveChat.png'),
    TextMessage_in: require('./support/TextMessage_in.png'),
    TextMessage: require('./support/TextMessage.png'),
    Videos_in: require('./support/Videos_in.png'),
    Videos: require('./support/Videos.png'),




}