export default {
    splashScreen: require('./img/intro.png'),
    logo: require('./img/logo.png'),
    slider1: require('./img/slider1.png'),
    slider2: require('./img/slider2.png'),
    slider3: require('./img/slider3.png'),
    slider4: require('./img/slider4.png'),
    backgroundLogin: require('./img/background.png'),
    checkBoxEmpty: require('./img/check-box-empty.png'),
    checkBox: require('./img/check-box.png'),
    sortDown: require('./img/down.png'),
    sortUp: require('./img/up.png'),
    indicate: require('./img/indicate.png'),
    addStaff: require('./img/addStaff.png'),
    closePopup: require('./img/closePopup.png'),
    logoTop: require('./img/fill-form-top.png'),
    camera: require('./img/camera.png'),
    iconUpload: require('./img/icon-upload.png'),
    signOut: require('./img/out.png'),
    openDrawer: require('./img/openDrawer.png'),
    plus: require('./img/plus.png'),
    sub: require('./img/sub.png'),
    calendar: require('./img/calendar.png'),
    iconItemBanner: require('./img/iconItemBanner.png'),
    deleteIconBanner: require('./img/deleteIconBanner.png'),
    arrowRight: require('./img/arrow_right.png'),
    search: require('./img/search.png'),
    export: require('./img/export.png'),
    dropdown: require('./img/dropdown.png'),
    arrowNote: require('./img/enter.png'),
    clearKeyboard: require('./img/clearKeyboard.png'),
    subKeyboard: require('./img/subKeyboard.png'),
    imagePlaceHolder: require('./img/imagePlaceHolder.png'),

    // --- drawer --
    Customer: require('./drawer/customer.png'),
    Home: require('./drawer/home.png'),
    Inventory: require('./drawer/inventory.png'),
    Invoice: require('./drawer/invoice.png'),
    Report: require('./drawer/report.png'),
    Setting: require('./drawer/setting.png'),
    Settlement: require('./drawer/settlement.png'),
    Support: require('./drawer/support.png'),

    // --- setting --
    General: require('./setting/General.png'),
    General_in: require('./setting/General_in.png'),
    Staff: require('./setting/Staff.png'),
    Staff_in: require('./setting/Staff_in.png'),
    Services: require('./setting/Services.png'),
    Services_in: require('./setting/Services_in.png'),
    Payment: require('./setting/Payment.png'),
    Payment_in: require('./setting/Payment_in.png'),
    Hardware: require('./setting/Hardware.png'),
    Hardware_in: require('./setting/Hardware_in.png'),
    About: require('./setting/About.png'),
    About_in: require('./setting/About_in.png'),
    Logout: require('./setting/Logout.png'),
    Logout_in: require('./setting/Logout_in.png'),
    Extra: require('./setting/Extra.png'),
    Extra_in: require('./setting/Extra_in.png'),
    Categories: require('./setting/Categories.png'),
    Categories_in: require('./setting/Categories_in.png'),

}