export default {
    splashScreen: require('./img/intro.png'),
    logo: require('./img/logo.png'),
    slider1: require('./img/slider1.png'),
    slider2: require('./img/slider2.png'),
    slider3: require('./img/slider3.png'),
    slider4: require('./img/slider4.png'),
    backgroundLogin: require('./img/background.png'),
    checkBoxEmpty: require('./img/check-box-empty.png'),
    checkBox: require('./img/check-box.png'),
    sortDown: require('./img/down.png'),
    sortUp: require('./img/up.png'),
    indicate: require('./img/indicate.png'),
    addStaff: require('./img/addStaff.png'),
    closePopup: require('./img/closePopup.png'),
    logoTop: require('./img/fill-form-top.png'),
    camera: require('./img/camera.png'),
    iconUpload: require('./img/icon-upload.png'),
    signOut: require('./img/out.png'),

    // --- drawer --
    Customer: require('./drawer/customer.png'),
    Home: require('./drawer/home.png'),
    Inventory: require('./drawer/inventory.png'),
    Invoice: require('./drawer/invoice.png'),
    Report: require('./drawer/report.png'),
    Setting: require('./drawer/setting.png'),
    Settlement: require('./drawer/settlement.png'),
    Support: require('./drawer/support.png'),
}