const strings = {
    firstName: 'Missing Info: First name',
    lastName: 'Missing Info: Last name',
    position: 'Missing Info: Title/Position',
    ownership: 'Missing Info: Ownership',
    homePhone: 'Missing Info: Home Phone',
    mobilePhone: 'Missing Info: Mobile Phone',
    address: 'Missing Info: Home address',
    city: 'Missing Info: City',
    state: 'Missing Info: State',
    zip: 'Missing Info: Zip',
    yearAtThisAddress: "Missing Info: Years at This Address",
    ssn: 'Missing Info: Social Security Number (SSN)',
    dateOfBirth: 'Missing Info: Date of Birth (mm/dd/yyyy)',
    day: 'Missing Info: Day of Birth (mm/dd/yyyy)',
    month: 'Missing Info: Month of Birth (mm/dd/yyyy)',
    year: 'Missing Info: Year of Birth (mm/dd/yyyy)',
    email: 'Missing Info: Email Address',
    driverLicense: 'Missing Info: Driver License Number',
    stateIssued: 'Missing Info: State Issued',
    homePhoneNotNumber: 'Home Phone Invalid',
    mobilePhoneNotNumber: 'Mobile Phone Invalid',
    yearAtThisAddressInvalid: 'Year At This Address Invalid',
    ssnInvalid: 'Social Security Number (SSN) Invalid',
    driverLicenseInvalid: 'Driver License Invalid',
    yearInvalid: 'Year Invalid',
    missAvatar: 'Please Upload Driver License',
    emailInvalid : 'Email Invalid',
    stateInvalid:"State Invalid!"
}

export default strings;