const strings = {
    firstName: 'Missing info : First name',
    lastName: 'Missing info : Last name',
    position: 'Missing info : Title/Position',
    ownership: 'Missing info : Ownership',
    homePhone: 'Missing info : Home Phone',
    mobilePhone: 'Missing info : Mobile Phone',
    address: 'Missing info : Home address',
    city: 'Missing info : City',
    state: 'Missing info : State',
    zip: 'Missing info : Zip',
    yearAtThisAddress: "Missing info : Years at This Address",
    ssn: 'Missing info : Social Security Number (SSN)',
    dateOfBirth: 'Missing info : Date of Birth (dd/mm/yy)',
    day: 'Missing info : Day of Birth (dd/mm/yy)',
    month: 'Missing info : Month of Birth (dd/mm/yy)',
    year: 'Missing info : Year of Birth (dd/mm/yy)',
    email: 'Missing info : Email Address',
    driverLicense: 'Missing info : Driver License Number',
    stateIssued: 'Missing info : State Issued',
    homePhoneNotNumber: 'Home Phone Invalid',
    mobilePhoneNotNumber: 'Mobile Phone Invalid',
    yearAtThisAddressInvalid: 'Year At This Address Invalid',
    ssnInvalid: 'Social Security Number (SSN) Invalid',
    driverLicenseInvalid: 'Driver License Invalid',
    yearInvalid: 'Year Invalid',
    missAvatar: 'Please Upload Driver License'
}

export default strings;