export const APP_TYPE = {
  POS: 'SalonPos',
  RETAILER: 'Retailer',
};

export const KEY_MENU = {
  MENU_HOME_TAB_MARKETING: 'MENU_HOME_TAB_MARKETING',
  MENU_HOME_TAB_CALENDAR: 'MENU_HOME_TAB_CALENDAR',
  MENU_HOME_TAB_CHECKOUT: 'MENU_HOME_TAB_CHECKOUT',
  MENU_HOME_TAB_CHECKOUT_DISCOUNT: 'MENU_HOME_TAB_CHECKOUT_DISCOUNT',
  MENU_INVOICE: 'MENU_INVOICE',
  MENU_SETTLEMENT: 'MENU_SETTLEMENT',
  MENU_CUSTOMER: 'MENU_CUSTOMER',
  MENU_GIFTCARD: 'MENU_GIFTCARD',
  MENU_INVENTORY: 'MENU_INVENTORY',
  MENU_REPORT: 'MENU_REPORT',
  MENU_SETTING: 'MENU_SETTING',
  MENU_SUPPORT: 'MENU_SUPPORT',
}
