# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

abstract_target 'Hpmerchant' do
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
 pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

# ----- npm ------
pod 'Fabric'
pod 'Crashlytics'
pod 'React', path: '../node_modules/react-native', subspecs: [
  'ART',
]

pod 'react-native-webview', :path => '../node_modules/react-native-webview'

pod 'RNSVG', :path => '../node_modules/react-native-svg'

pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'

pod 'RNStarPrnt', :path => '../node_modules/react-native-star-prnt'
  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker/RNDateTimePicker.podspec'
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
pod 'XCDYouTubeKit', '~> 2.8'

pod 'RCTYouTube', :path => '../node_modules/react-native-youtube'
pod 'CodePush', :path => '../node_modules/react-native-code-push'
pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'



pod 'RNPermissions', :path => '../node_modules/react-native-permissions'


pod 'react-native-camera', :path => '../node_modules/react-native-camera'
pod 'react-native-version-check', :path => '../node_modules/react-native-version-check'

permissions_path = '../node_modules/react-native-permissions/ios'
pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"

pod 'react-native-view-shot', :path => '../node_modules/react-native-view-shot'

pod 'react-native-config', :path => '../node_modules/react-native-config'

pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end

    if target.name == "yoga"
      target.remove_from_project
    end
  end
end

# -------------- Multi Schema ------------

target 'Hpmerchant_Production' do

end

target 'Hpmerchant_Staging' do

end

target 'Hpmerchant_Dev' do

end


end





