export const role = {
    Manager: 'Manager',
    Admin: 'Admin',
  }
  
export const menuTabs = {
    MARKETING: 'MENU_HOME_TAB_MARKETING',
    CHECKOUT_DISCOUNT: 'MENU_HOME_TAB_CHECKOUT_DISCOUNT',
    MENU_INVOICE: 'MENU_INVOICE',
    MENU_SETTLEMENT: 'MENU_SETTLEMENT',
    MENU_CUSTOMER: 'MENU_CUSTOMER',
    MENU_GIFTCARD: 'MENU_GIFTCARD',
    MENU_INVENTORY: 'MENU_INVENTORY',
    MENU_REPORT: 'MENU_REPORT',
    MENU_SETTING: 'MENU_SETTING',
}

export const REMOTE_APP_ID = 'JCAQ6671XBR3Y.7YXHTNM6RYMVT'
export const APP_NAME = 'HarmonyPOS'
export const POS_SERIAL = "POS-1"

