const localization = {
    'en': {
        'MARKETING': 'MARKETING',
        'APPOINTMENT': 'APPOINTMENT',
        'CHECKOUT': 'CHECKOUT',
        'Promotions':'Promotions',
        'Custom Banner':'Custom Banner',
        'Custom Marketing':'Custom Marketing',
        'Thank you for submitting application, one of our agent will':'Thank you for submitting application, one of our agent will',
        'contact you within the next business day.':'contact you within the next business day.',
        'FINISH':'FINISH',
        'Bank Information':'Bank Information',
        'ABA Routing Number *':'ABA Routing Number *',
        'Checking Account Number (DDA) *':'Checking Account Number (DDA) *',
        'Void Check *':'Void Check *',
        'Please take or upload photos of void check':'Please take or upload photos of void check',
        'Take a Photo':'Take a Photo',
        'Or':'Or',
        'Browse File':'Browse File',
        'File Upload':'File Upload',
        'Do you want to Archive this Category ?':'Do you want to Archive this Category ?',
        'Business Information':'Business Information',
        'Have You Ever Accepted Credit/Debit Cards Before?':'Have You Ever Accepted Credit/Debit Cards Before?',
        'if yes, who was the processor':'if yes, who was the processor',
        'Has a Processor Ever Terminated Your Merchant Account?':'Has a Processor Ever Terminated Your Merchant Account?',
        'if yes, who was the processor':'if yes, who was the processor',
        'Has Merchant or any associated principal and/or owners disclosed below filed bankruptcy or been subject to any involuntary bankruptcy?':'Has Merchant or any associated principal and/or owners disclosed below filed bankruptcy or been subject to any involuntary bankruptcy?',
        'if yes, date filed':'if yes, date filed',
        'Has Merchant been previously identified by Visa/Mastercard Risk Programs?':'Has Merchant been previously identified by Visa/Mastercard Risk Programs?',
        'if yes, was program and when':'if yes, was program and when',
        'Will Product(s) or Service(s) Be Sold Outside of The U.S ?':'Will Product(s) or Service(s) Be Sold Outside of The U.S ?',
    },
    'vi': {
        'MARKETING': 'Uu dai',
        'APPOINTMENT': 'Quan ly uu dai',
        'CHECKOUT': 'Quan Ly Kinh doanh',
        'Promotions':'Promotions ',
        'Custom Banner':'Custom Banner',
        'Custom Marketing':'Custom Marketing',
        'Thank you for submitting application, one of our agent will':'',
        'contact you within the next business day.':'',
        'FINISH':'',
        'Bank Information':'',
        'ABA Routing Number *':'',
        'Checking Account Number (DDA) *':'',
        'Void Check *':'',
        'Please take or upload photos of void check':'',
        'Take a Photo':'Take a Photo',
        'Or':'',
        'Browse File':'',
        'File Upload':'',
        'Do you want to Archive this Category ?':'',
        'Business Information':'',
        'Have You Ever Accepted Credit/Debit Cards Before?':'',
        'if yes, who was the processor':'',
        'Has a Processor Ever Terminated Your Merchant Account?':'',
        'if yes, who was the processor':'',
        'Has Merchant or any associated principal and/or owners disclosed below filed bankruptcy or been subject to any involuntary bankruptcy?':'',
        'if yes, date filed':'',
        'Has Merchant been previously identified by Visa/Mastercard Risk Programs?':'',
        'if yes, was program and when':'if yes, was program and when',
        'Will Product(s) or Service(s) Be Sold Outside of The U.S ?':''
    }
}

export default localization;