const localization = {
  en: {
    "MARKETING": "MARKETING",
    "APPOINTMENT": "APPOINTMENT",
    "CHECKOUT": "CHECKOUT",
    "Promotions": "Promotions",
    "Custom Banner": "Custom Banner",
    "Custom Marketing": "Custom Marketing",
    "Thank you for submitting your application, one of our agent will":
      "Thank you for submitting your application, one of our agent will",
    "contact you within the next business day":
      "contact you within the next business day",
    "FINISH": "FINISH",
    "Bank Information": "Bank Information",
    "ABA Routing Number": "ABA Routing Number",
    "Checking Account Number (DDA)": "Checking Account Number (DDA)",
    "Void Check": "Void Check",
    "Please take or upload photos of void check":
      "Please take or upload photos of void check",
    "Take a Photo": "Take a Photo",
    "Or": "Or",
    "Browse File": "Browse File",
    "File Upload": "File Upload",
    "Do you want to Archive this Category":
      "Do you want to Archive this Category",
    "Business Information": "Business Information",
    "Have You Ever Accepted Credit/Debit Cards Before?":
      "Have You Ever Accepted Credit/Debit Cards Before?",
    "Has a Processor Ever Terminated Your Merchant Account?":
      "Has a Processor Ever Terminated Your Merchant Account?",
    "if yes, who was the processor": "if yes, who was the processor",
    "Has Merchant or any associated principal and/or owners disclosed below filed bankruptcy or been subject to any involuntary bankruptcy?":
      "Has Merchant or any associated principal and/or owners disclosed below filed bankruptcy or been subject to any involuntary bankruptcy?",
    "if yes, date filed": "if yes, date filed",
    "Has Merchant been previously identified by Visa/Mastercard Risk Programs?":
      "Has Merchant been previously identified by Visa/Mastercard Risk Programs?",
    "if yes, was program and when": "if yes, was program and when",
    "Will Product(s) or Service(s) Be Sold Outside of The U.S ?":
      "Will Product(s) or Service(s) Be Sold Outside of The U.S ?",
    "CONGRATULATION": "CONGRATULATION",
    "Your account is ready to operate": "Your account is ready to operate",
    "Forgot Password": "Forgot Password",
    "Please enter your email address and we will send you":
      "Please enter your email address and we will send you",
    "instructions on how to reset your password": "instructions on how to reset your password",
    "SUBMIT": "SUBMIT",
    "General Information": "General Information",
    "Legal Business Name": "Legal Business Name",
    "as shown on your income tax return": "as shown on your income tax return",
    "Doing Business As Name (DBA)": "Doing Business As Name (DBA)",
    "Federal Tax ID": "Federal Tax ID",
    "DBA Business Address": "DBA Business Address",
    "Business Phone Number": "Business Phone Number",
    "Contact Email Address": "Contact Email Address",
    "Contact Name": "Contact Name",
    "Title/Position": "Title/Position",
    "Contact Phone Number *": "Contact Phone Number *",
    "APPLY": "APPLY",
    "Discount according to the time frame":
      "Discount according to the time frame",
    "Campaign Name": "Campaign Name",
    "Campaign Time": "Campaign Time",
    "Select Start Date ": "Select Start Date ",
    "Select End Date": "Select End Date",
    "From": "From",
    "To": "To",
    "Promotion form:": "Promotion form:",
    "Discount by percent": "Discount by percent",
    "Discount fixtom amount ($)": "Discount fixtom amount ($)",
    "Discount when using the following services":
      "Discount when using the following services",
    "Discount on birthday": "Discount on birthday",
    "Discount for referrals": "Discount for referrals",
    "Media List": "Media List",
    "Create new media": "Create new media",
    "NEXT": "NEXT",
    "Skip": "Skip",
    "Booking Management": "Booking Management",
    "POS System": "POS System",
    "Marketing": "Marketing",
    "Report And Management": "Report And Management",
    "APPLICATION": "APPLICATION",
    "DEMO": "DEMO",
    "BookingDes": " Fun and interactive booking with your favorite stylists!",
    "PosDes":"Pay and tip your stylist from anywhere - even if you forget your cards! ",
    "MarketingDes": "Get exclusive deals from all your favorite stores!",
    "ReportDes":"I thought the last feature for Consumer App was Peer-to-Peer. What is Report and Manager?",
    "Principal Des":"Provide the following information for each individual who owns, directly or indirectly 25% or more of the equity interest of your business.",
    "Principal Information": "Principal Information",
    "Principal Name": "Principal Name",
    "First name": "First name",
    "Last name": "Last name",
    "Manager": "Manager",
    "Ownership": "Ownership",
    "Home Phone": "Home Phone",
    "Mobile Phone": "Mobile Phone",
    "Home address": "Home address",
    "City": "City",
    "State": "State",
    "Years at This Address": "Years at This Address",
    "Date of Birth": "Date of Birth",
    "day": "day",
    "Month": "Month",
    "Year": "Year",
    "Email Address": "Email Address",
    "Driver License Number": "Driver License Number",
    "State Issued": " State Issued",
    "Please take or upload photos of Driver License":
      "Please take or upload photos of Driver License",
    "password": "password",
    "Sign up": "Sign up",
    "Home": "Home",
    "Invoice": "Invoice",
    "Settlement": "Settlement",
    "Customer": "Customer",
    "Inventory": "Inventory",
    "Report": "Report",
    "Setting": "Setting",
    "Support": "Support",
    "Store Info": "Store Info",
    "Admin Info": "Admin Info",
    "Staff Management": "Staff Management",
    "Business Name": "Business Name",
    "Business Address": "Business Address",
    "Federal Tax Id": "Federal Tax Id",
    "Phone Number": "Phone Number",
    "Bank Name": "Bank Name",
    "Account Number": "Account Number",
    "Routing Number": "Routing Number",
    "First Name": "First Name",
    "Last Name": "Last Name",
    "Display Name": "Display Name",
    "Address": "Address",
    "Street": "Street",
    "Cell phone": "Cell phone",
    "Contact email": "Contact email",
    "Email": "Email",
    "Create PIN": "Create PIN",
    "Confirm PIN": "Confirm PIN",
    "Admin": "Admin",
    "Working Time": "Working Time",
    "Salary": "Salary",
    "Tip fee": "Tip fee",
    "Percent": "Percent",
    "Fixed Amount": "Fixed Amount",
    "Driver License": "Driver License",
    "Social security number": "Social security number",
    "Professional license": "Professional license",
    "Forgot your PIN": "Forgot your PIN",
    "START": "START",
    "Don’t have a PIN code ? ": "Don’t have a PIN code ? ",
    "PIN code": "PIN code",
    "Search": "Search",
    "Add New": "Add New",
    "Filters": "Filters",
    "SKU Number": "SKU Number",
    "Product Name": "Product Name",
    "Scan SKU": "Scan SKU",
    "Select All": "Select All",
    "Restock": "Restock",
    "Export": "Export",
    "Cteategories": "Cteategories",
    "Customer Name": "Customer Name",
    "Phone number": "Phone number",
    "Customer List": "Customer List",
    "Referrer Phone Number": "Referrer Phone Number",
    "Service": "Service",
    "Product": "Product",
    "Enter the amount of product added": "Enter the amount of product added",
    "Submit": "Submit",
    "Extra Name": "Extra Name",
    "Language": "Language",
    "Auto close": "Auto close",
    "Auto close at": "Auto close at",
    "Auto lock screen after": "Auto lock screen after",
    "SAVE": "SAVE",
    "Terms of Service": "Terms of Service",
    "ACCEPT": "ACCEPT",
    "USER GUIDE": "USER GUIDE",
    "ANIMATION": "ANIMATION",
    "Please fill the form below": "Please fill the form below",
    "DBA address": "DBA address",
    "Zip": "Zip",
    "Contact Phone Number": "Contact Phone Number",
    "Principal": "Principal",
    "Day Of Birth": "Day Of Birth",
    "Social Security Number (SSN)": "Social Security Number (SSN)",
    "Forgot password": "Forgot password",
    "SIGN IN": "SIGN IN",
    "Don’t have an account": "Don’t have an account",
    "Back": "Back",
    "Your pin code": "Your pin code",
    "Please check your internet": "Please check your internet",
    "Do you want use offline mode": "Do you want use offline mode",
    "Ask me later": "Ask me later",
    "OK": "OK",
    "Select From Date": "Select From Date",
    "Promotion": "Promotion",
    "Discount fix amount": "Discount fix amount",
    "Send Notification": "Send Notification",
    "Promotional Services": "Promotional Services",
    "Using": "Using",
    "Services": "Services",
    "Apply to": "Apply to",
    "Promotion applied on (times)": "Promotion applied on (times)",
    "Title": "Title",
    "Description": "Description",
    "Confirmation": "Confirmation",
    "Do you want to Delete this Banner": "Do you want to Delete this Banner",
    "Phone": "Phone",
    "Extra": "Extra",
    "Amount": "Amount",
    "ADD": "ADD",
    "Basket": "Basket",
    "Subtotal": "Subtotal",
    "Tip": "Tip",
    "Tax": "Tax",
    "Discount": "Discount",
    "Apply Discount": "Apply Discount",
    "Discount by Owner": "Discount by Owner",
    "Discount by Staff": "Discount by Staff",
    "Discount Campaigns:": "Discount Campaigns:",
    "Discount Items:": "Discount Items:",
    "Apply Value": "Apply Value",
    "Manual Discount": "Manual Discount",
    "Total": "Total",
    "BOOK": "BOOK",
    "Are you sure you want to exit Check-Out? ": "Are you sure you want to exit Check-Out? ",
    "Change Stylist": "Change Stylist",
    "Stylist": "Stylist",
    "Name": "Name",
    "Tip ($)": "Tip ($)",
    "Total Discount": "Total Discount",
    "Custom Discount by": "Custom Discount by",
    "Custom Discount by fixed amount": "Custom Discount by fixed amount",
    "Print receipt": "Print receipt",
    "Open Cash Drawer": "Open Cash Drawer",
    "Paid": "Paid",
    "Due amount": "Due amount",
    "CANCEL": "CANCEL",
    "DONE": "DONE",
    "PAY": "PAY",
    "CONFIRM": "CONFIRM",
    "SELECT PAYMENT": "SELECT PAYMENT",
    "Select payment method": "Select payment method",
    "BACK": "BACK",
    "Offline mode": "Offline mode",
    "Use consumer app to scan QR code below":
      "Use consumer app to scan QR code below",
    "Then scan the QR code on the phone": "Then scan the QR code on the phone",
    "to complete the transaction": "to complete the transaction",
    "Bill of payment": "Bill of payment",
    "Active Gift Card": "Active Gift Card",
    "Customer Phone": "Customer Phone",
    "Payment Details": "Payment Details",
    "Please wait": "Please wait",
    "Transaction is processing": "Transaction is processing",
    "Cancel": "Cancel",
    "Invoice No": "Invoice No",
    "Grand Total": "Grand Total",
    "Paid Amount": "Paid Amount",
    "Due Amount": "Due Amount",
    "Next": "Next",
    "Exact": "Exact",
    "Done": "Done",
    "Invoice No / SKU number/Phone number / Customer Name":
      "Invoice No / SKU number/Phone number / Customer Name",
    "Time Range": "Time Range",
    "Payment Method": "Payment Method",
    "HP-Harmony Account": "HP-Harmony Account",
    "HP-Credit Card": "HP-Credit Card",
    "Credit Card": "Credit Card",
    Cash: "Cash",
    "Cheque/Bank Transfer": "Cheque/Bank Transfer",
    Status: "Status",
    Pending: "Pending",
    Void: "Void",
    Refund: "Refund",
    VOID: "VOID",
    "Customer name": "Customer name",
    Date: "Date",
    Time: "Time",
    "Total amount": "Total amount",
    "Created by": "Created by",
    "Modified by": "Modified by",
    "Payment information": "Payment information",
    History: "History",
    "Payment method": "Payment method",
    "CC type": "CC type",
    "CC number": "CC number",
    "CC exp": "CC exp",
    "Invoice List": "Invoice List",
    "List Empty": "List Empty",
    "Invoice Detail": "Invoice Detail",
    "Input PIN Number": "Input PIN Number",
    "Batch Settlements": "Batch Settlements",
    "Last Settlement": "Last Settlement",
    "Staff List": "Staff List",
    "Staff Statistic": "Staff Statistic",
    "Total Amount": "Total Amount",
    "Time/Amount": "Time/Amount",
    "Report Amount": "Report Amount",
    "Payment by Harmony account": "Payment by Harmony account",
    "Payment by Credit card": "Payment by Credit card",
    "Payment by Cash": "Payment by Cash",
    "Other payment": "Other payment",
    "Editable Actual Amount": "Editable Actual Amount",
    "Empty Batch": "Empty Batch",
    "Pull to refresh": "Pull to refresh",
    "Open Batch": "Open Batch",
    "Log message": "Log message",
    "Batch Settlement Successful": "Batch Settlement Successful",
    "REVIEW BATCH HISTORY": "REVIEW BATCH HISTORY",
    SETTLE: "SETTLE",
    Transactions: "Transactions",
    "Actual Amount": "Actual Amount",
    Note: "Note",
    "Invoice No / SKU number/customer phone number":
      "Invoice No / SKU number/customer phone number",
    "Transactions ID": "Transactions ID",
    "Date Time": "Date Time",
    "Invoice Number": "Invoice Number",
    Payment: "Payment",
    "View Log Detail": "View Log Detail",
    "Log Detail": "Log Detail",
    "Batch ID": "Batch ID",
    "New Customer": "New Customer",
    "Edit Customer": "Edit Customer",
    "Customer Details": "Customer Details",
    Referrer: "Referrer",
    "Note about customer's favourite": "Note about customer's favourite",
    Edit: "Edit",
    Categories: "Categories",
    "Handle the downloaded file": "Handle the downloaded file",
    "Export to excel": "Export to excel",
    "Product Details": "Product Details",
    "Edit Product": "Edit Product",
    Save: "Save",
    "Add Product": "Add Product",
    "Add Item to Stock": "Add Item to Stock",
    "SKU number": "SKU number",
    Quantity: "Quantity",
    "Need to order": "Need to order",
    "Low theshold": "Low theshold",
    "Max theshold": "Max theshold",
    Archive: "Archive",
    Restore: "Restore",
    "Do you want to Archive this Product":
      "Do you want to Archive this Product",
    "Do you want to Restore this Product":
      "Do you want to Restore this Product",
    "Save as": "Save as",
    "The products need to order more": "The products need to order more",
    "All product": "All product",
    "Excel file is being created": "Excel file is being created",
    Reports: "Reports",
    "Compare sales of Staffs": "Compare sales of Staffs",
    No: "No",
    Split: "Split",
    Settings: "Settings",
    "Are you sure you want to Log out": "Are you sure you want to Log out",
    "Catgory Name": "Catgory Name",
    "Category Type": "Category Type",
    "Add Category": "Add Category",
    "Edit Category": "Edit Category",
    "Do you want to Restore this Category":
      "Do you want to Restore this Category",
    Type: "Type",
    Actions: "Actions",
    "Add Extra": "Add Extra",
    Add: "Add",
    "Edit Extra": "Edit Extra",
    "Do you want to Archive this Extra": "Do you want to Archive this Extra",
    "Do you want to Restore this Extra": "Do you want to Restore this Extra",
    Price: "Price",
    Website: "Website",
    "Business Hours": "Business Hours",
    Longtitude: "Longtitude",
    Latitude: "Latitude",
    "Get current your position": "Get current your position",
    "Contact Email": "Contact Email",
    "Merchant ID": "Merchant ID",
    "No connected device": "No connected device",
    "Add device": "Add device",
    "Payment Terminal": "Payment Terminal",
    "Connected Device": "Connected Device",
    "Payment terminal": "Payment terminal",
    "Terminal Configuration": "Terminal Configuration",
    "Device name": "Device name",
    "IP Address": "IP Address",
    "Add Service": "Add Service",
    "Edit Service": "Edit Service",
    "Do you want to Archive this Service":
      "Do you want to Archive this Service",
    "Do you want to Restore this Service":
      "Do you want to Restore this Service",
    "Service Name": "Service Name",
    "Staff Name": "Staff Name",
    Role: "Role",
    "LOG OUT": "LOG OUT",
    "Contact information": "Contact information",
    Hotline: "Hotline",
    "Services / Products": "Services / Products",
    "Service Salary": "Service Salary",
    "Per Hour": "Per Hour",
    Commission: "Commission",
    "Product Salary": "Product Salary",
    "Do you want to Archive this Staff": "Do you want to Archive this Staff",
    "Do you want to Restore this Staff": "Do you want to Restore this Staff",
    Products: "Products",
    "Category Name": "Category Name",
    "Gel Nails": "Gel Nails",
    Duration: "Duration",
    Category: "Category",
    "Items in stock": "Items in stock",
    WorkingHour: "Working Hour",
    ProductPayout: "Product Payout",
    ServicePayout: "Service Payout",
    Tippayout: "Tip Payout",
    "Staff Salary": "Staff Salary",
    "Accessibility": "Accessibility",
    "Tabs": "Tabs",
    "Calendar": "Calendar",
    "Checkout": "Checkout",
    "Change Discount": "Change Discount",
    "Gift card": "Gift card",
    DiscountByStaff: "Discount By Staff",
    "PleaseWait": "Please wait!",
    "NoEndDate": "No end date",
    "VerifyPayment": "Verify payment",
    "VerifyPaymentMessage": "This may be a duplicate, do you want to accept this payment?",
    "Accept": "Accept",
    "Reject": "Reject",
    "Serial Number": "Serial Number",
    "Dejavoo": "Dejavoo",
    "Auth Key": "Auth Key",
    "Register ID": "Register ID",
    "Your transaction is invalid": "Your transaction is invalid",
    "ManualDiscountNote": "(Note: Manual Discount will replace Promotion Discount.)"
  },
  vi: {},
};

export default localization;
