const localization = {
    'en': {
        'MARKETING': 'MARKETING',
        'APPOINTMENT': 'APPOINTMENT',
        'CHECKOUT': 'CHECKOUT',
        'Promotions': 'Promotions',
        'Custom Banner': 'Custom Banner',
        'Custom Marketing': 'Custom Marketing',
        'Thank you for submitting application, one of our agent will': 'Thank you for submitting application, one of our agent will',
        'contact you within the next business day.': 'contact you within the next business day.',
        'FINISH': 'FINISH',
        'Bank Information': 'Bank Information',
        'ABA Routing Number *': 'ABA Routing Number *',
        'Checking Account Number (DDA) *': 'Checking Account Number (DDA) *',
        'Void Check *': 'Void Check *',
        'Please take or upload photos of void check': 'Please take or upload photos of void check',
        'Take a Photo': 'Take a Photo',
        'Or': 'Or',
        'Browse File': 'Browse File',
        'File Upload': 'File Upload',
        'Do you want to Archive this Category ?': 'Do you want to Archive this Category ?',
        'Business Information': 'Business Information',
        'Have You Ever Accepted Credit/Debit Cards Before?': 'Have You Ever Accepted Credit/Debit Cards Before?',
        'if yes, who was the processor': 'if yes, who was the processor',
        'Has a Processor Ever Terminated Your Merchant Account?': 'Has a Processor Ever Terminated Your Merchant Account?',
        'if yes, who was the processor': 'if yes, who was the processor',
        'Has Merchant or any associated principal and/or owners disclosed below filed bankruptcy or been subject to any involuntary bankruptcy?': 'Has Merchant or any associated principal and/or owners disclosed below filed bankruptcy or been subject to any involuntary bankruptcy?',
        'if yes, date filed': 'if yes, date filed',
        'Has Merchant been previously identified by Visa/Mastercard Risk Programs?': 'Has Merchant been previously identified by Visa/Mastercard Risk Programs?',
        'if yes, was program and when': 'if yes, was program and when',
        'Will Product(s) or Service(s) Be Sold Outside of The U.S ?': 'Will Product(s) or Service(s) Be Sold Outside of The U.S ?',
        'CONGRATULATION !': 'CONGRATULATION !',
        'Your account is ready to operate': 'Your account is ready to operate',
        'Forgot Password': 'Forgot Password',
        'Please enter your email address and we will send you': 'Please enter your email address and we will send you',
        'instructions on how to reset your password': 'instructions on how to reset your password',
        'SUBMIT': 'SUBMIT',
        'General Information': 'General Information',
        'Legal Business Name * ': 'Legal Business Name * ',
        '(as shown on your income tax return)': '(as shown on your income tax return)',
        'Doing Business As Name (DBA) *': 'Doing Business As Name (DBA) *',
        'Federal Tax ID *': 'Federal Tax ID *',
        'DBA Business Address *': 'DBA Business Address *',
        'Business Phone Number *': 'Business Phone Number *',
        'Contact is  Email Address *': 'Contact is  Email Address *',
        'Contact Name *': 'Contact Name *',
        'Title/Position *': 'Title/Position *',
        'Contact is Phone Number *': 'Contact is Phone Number *',
        'APPLY': 'APPLY',
        'Discount according to the time frame': 'Discount according to the time frame',
        'Campaign Name:': 'Campaign Name:',
        'Campaign Time:': 'Campaign Time:',
        'Start Date': 'Start Date',
        'End Date': 'End Date',
        'From': 'From',
        'To': 'To',
        'Promotion form:': 'Promotion form:',
        'Discount by percent (%)': 'Discount by percent (%)',
        'Discount fixtom amount ($)': 'Discount fixtom amount ($)',
        'Discount when using the following services': 'Discount when using the following services',
        'Discount on birthday': 'Discount on birthday',
        'Discount for referrals': 'Discount for referrals',
        'Media List': 'Media List',
        'Create new media': 'Create new media',
        'NEXT': 'NEXT',
        'Skip': 'Skip',
        'Booking Management': 'Booking Management',
        'POS System': 'POS System',
        'Marketing': 'Marketing',
        'Report And Management': 'Report And Management',
        'APPLICATION': 'APPLICATION',
        'DEMO': 'DEMO',
        'BookingDes': "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1 500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        'PosDes': "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1 500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        'MarketingDes': "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1 500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        'ReportDes': "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1 500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        'Principal Des' :'Provide the following information for each individual who owns, directly or indirectly,25% or more of the equity interest of your business.',
        'Principal Information':'Principal Information',
        'Principal Name *':'Principal Name *',
        'First name':'First name',
        'Last name':'Last name',
        'Manager':'Manager',
        'Ownership (%) *':'Ownership (%) *',
        'Home Phone *':'Home Phone *',
        'Mobile Phone':'Mobile Phone',
        'Address *':'Address *',
        'Home address':'Home address',
        'City':'City',
        'State':'State',
        'Years at This Address *':'Years at This Address *',
        'Date of Birth (dd/mm/yy) *':'Date of Birth (dd/mm/yy) *',
        'day':'day',
        'Month':'Month',
        'Year':'Year',
        'Email Address *':'Email Address *',
        'Driver License Number *':'Driver License Number *',
        'State Issued *':' State Issued *',
        'Please take or upload photos of Driver License':'Please take or upload photos of Driver License',
        'password':'password',
        'Sign up':'Sign up',
        'Don’t have an account? ' :'Don’t have an account? ',
        'Home':'Home',
        'Invoice':'Invoice',
        'Settlement':'Settlement',
        'Customer':'Customer',
        'Inventory':'Inventory',
        'Report':'Report',
        'Setting':'Setting',
        'Support':'Support',
        'Store Info':'Store Info',
        'Admin Info':'Admin Info',
        'Staff Management':'Staff Management',
        'Business Name':'Business Name',
        'Business Address':'Business Address',
        'Federal Tax Id':'Federal Tax Id',
        'Phone Number':'Phone Number',
        'Contact Email':'Contact Email',
        'Bank Name':'Bank Name',
        'Account Number':'Account Number',
        'Routing Number':'Routing Number',
        'Name':'Name',
        'First Name':'First Name',
        'Last Name':'Last Name',
        'Display Name':'Display Name',
        'Address':'Address',
        'Street':'Street',
        'Cell phone':'Cell phone',
        'Contact email':'Contact email',
        'Email':'Email',
        'Create PIN':'Create PIN',
        'Confirm PIN':'Confirm PIN',
        'Admin':'Admin',
        'Working time':'Working time',
        'Salary':'Salary',
        'Per hour':'Per hour',
        'Commission':'Commission',
        'Tip fee':'Tip fee',
        'Percent':'Percent',
        'Fixed amount':'Fixed amount',
        'Driver license':'Driver license',
        'Social security number':'Social security number',
        'Professional license':'Professional license',
        'Forgot your PIN':'Forgot your PIN',
        'START':'START',
        'Don’t have a PIN code ? ':'Don’t have a PIN code ? ',
        'PIN code' :'PIN code',
        'Search':'Search',
        'Add New':'Add New',
        'Filters':'Filters',
        'Staff Name':'Staff Name',
        'Role':'Role',
        'Statuses':'Statuses',
    },
    'vi': {
        'MARKETING': 'Uu dai',
        'APPOINTMENT': 'Quan ly uu dai',
        'CHECKOUT': 'Quan Ly Kinh doanh',
        'Promotions': 'Promotions ',
        'Custom Banner': 'Custom Banner',
        'Custom Marketing': 'Custom Marketing',
        'Thank you for submitting application, one of our agent will': '',
        'contact you within the next business day.': '',
        'FINISH': '',
        'Bank Information': '',
        'ABA Routing Number *': '',
        'Checking Account Number (DDA) *': '',
        'Void Check *': '',
        'Please take or upload photos of void check': '',
        'Take a Photo': 'Take a Photo',
        'Or': '',
        'Browse File': '',
        'File Upload': '',
        'Do you want to Archive this Category ?': '',
        'Business Information': '',
        'Have You Ever Accepted Credit/Debit Cards Before?': '',
        'if yes, who was the processor': '',
        'Has a Processor Ever Terminated Your Merchant Account?': '',
        'if yes, who was the processor': '',
        'Has Merchant or any associated principal and/or owners disclosed below filed bankruptcy or been subject to any involuntary bankruptcy?': '',
        'if yes, date filed': '',
        'Has Merchant been previously identified by Visa/Mastercard Risk Programs?': '',
        'if yes, was program and when': 'if yes, was program and when',
        'Will Product(s) or Service(s) Be Sold Outside of The U.S ?': '',
        'CONGRATULATION !': '',
        'Your account is ready to operate': '',
        'Forgot Password': '',
        'Please enter your email address and we will send you': '',
        'instructions on how to reset your password': '',
        'SUBMIT': '',
        'General Information': '',
        'Legal Business Name * ': 'Legal Business Name * ',
        '(as shown on your income tax return)': '(as shown on your income tax return)',
        'Doing Business As Name (DBA) *': '',
        'Federal Tax ID *': 'Federal Tax ID *',
        'DBA Business Address *': 'DBA Business Address *',
        'Business Phone Number *': 'Business Phone Number *',
        'Contact is  Email Address *': '',
        'Contact Name *': '',
        'Title/Position *': '',
        'Contact is Phone Number *': 'Contact is Phone Number *',
        'APPLY': '',
        'Discount according to the time frame': '',
        'Campaign Name:': '',
        'Campaign Time:': '',
        'Start Date': '',
        'End Date': 'End Date',
        'From': '',
        'To': '',
        'Promotion form:': '',
        'Discount by percent (%)': '',
        'Discount fixtom amount ($)': '',
        'Discount when using the following services': '',
        'Discount on birthday': '',
        'Discount for referrals': '',
        'Media List': '',
        'Create new media': 'Create new media',
        'NEXT': '',
        'Skip': '',
        'Booking Management': '',
        'POS System': '',
        'Marketing': '',
        'Report And Management': '',
        'APPLICATION': '',
        'DEMO': '',
        'BookingDes': "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1 500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        'PosDes': "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1 500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        'MarketingDes': "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1 500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        'ReportDes': "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1 500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        'Principal Des':'',
        'Principal Information':'Principal Information',
        'Principal Name *':'',
        'First name':'',
        'Last name':'',
        'Manager':'',
        'Ownership (%) *':'',
        'Home Phone *':'',
        'Home':'Trang chủ',
        'Invoice':'Đơn hàng',
        'Settlement':'Settlement',
        'Customer':'Khách Hàng',
        'Inventory':'Tồn kho',
        'Report':'Báo cáo',
        'Setting':'Cài đăt',
        'Support':'Hỗ trợ',
    }
}

export default localization;